---
# this is just a test
- name: This is a hello-world example
  hosts: all
  tasks:
    - debug:
        msg: "Hello World!"
        
    - name: Set a variable for the api response to recevied
      set_stats:
       data:
        Sonar_url: "http://www.sonar.com"
